apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  labels:
    app: fastapi-inference

spec:
  selector:
    app: fastapi-inference

  type: LoadBalancer

  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP