# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"\x1c\n\x0cInferRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x02\":\n\rInferResponse\x12\x0e\n\x06logits\x18\x01 \x03(\x02\x12\x19\n\x11predicted_classes\x18\x02 \x01(\x05\x32N\n\x10InferenceService\x12:\n\x05Infer\x12\x17.inference.InferRequest\x1a\x18.inference.InferResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFERREQUEST']._serialized_start=30
  _globals['_INFERREQUEST']._serialized_end=58
  _globals['_INFERRESPONSE']._serialized_start=60
  _globals['_INFERRESPONSE']._serialized_end=118
  _globals['_INFERENCESERVICE']._serialized_start=120
  _globals['_INFERENCESERVICE']._serialized_end=198
# @@protoc_insertion_point(module_scope)
